### ISSUE TITLE
Cannot grab calamares package : Maximum file size exceeded

### ISSUE THREAD

**Issue by FredBezies** [endeavouros-team/archiso-offlineinstaller#1]
Hello.

I tried to create an installation ISO following your guide. I installed in a virtualbox virtual machine EndeavourOS Beta 2.1.

After I updated my installation, I followed your guide. Here is the error I got every single time I tried to build your ISO:

```
 ckbcomp-1.184-1-any       26,2 KiB   270K/s 00:00 [----------------------] 100%
error: failed retrieving file 'calamares_offline-1-1-any.pkg.tar.xz' from github.com : Maximum file size exceeded
error: failed retrieving file 'calamares_offline-1-1-any.pkg.tar.xz' from sourceforge.net : Maximum file size exceeded
warning: failed to retrieve some files
 kalu-4.3.0-3-x86_64      200,2 KiB   659K/s 00:00 [----------------------] 100%
 yay-9.2.0-1-x86_64      1971,7 KiB  2012K/s 00:01 [----------------------] 100%
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
==> ERROR: Failed to install packages to new root
```

Of course, build install process is stopped right after this bug. Any idea?

**Comment by FredBezies** [comment]
Forget to add: yay is grabbed flawlessly.

```
[fred@fredo-endos pkg]$ pwd
/var/cache/pacman/pkg
[fred@fredo-endos pkg]$ ls ya*
yaml-cpp-0.6.2-1-x86_64.pkg.tar.xz  yay-9.2.0-1-x86_64.pkg.tar.xz
[fred@fredo-endos pkg]$ 
```

**Comment by killajoe** [comment]
Hi nice to see you involved and interested!
This was an issue with the calamares package itself (versioning) and is solved now.

If you find any issues or ideas/solutions for improvement we would be happy to get informed here!
help is must welcomed!
