### ISSUE TITLE
[Wish] Adding and enabling by default ublock origin in Mozilla Firefox

### ISSUE THREAD

**Issue by FredBezies** [endeavouros-team/archiso-offlineinstaller#3]
It could be a great idea to add and activate by default ublock-origin in Mozilla Firefox. You'll only need to add firefox-ublock-origin package in packages.x86_64.

It adds only 3 mb in the final ISO. Nearly nothing but you can help improving user privacy this way.

**Comment by killajoe** [comment]
I do vote for firefox-ublock-origin also, we will discuss this, and if we are positive with it i will add it.

**Comment by killajoe** [comment]
done for next beta /try out
