### ISSUE TITLE
Missing wallpaper only in live environment.

### ISSUE THREAD

**Issue by FredBezies** [endeavouros-team/archiso-offlineinstaller#4]
I generate an ISO a few minutes ago, and I noticed there is no wallpaper in live environment.

Here is a screenshot taken in VirtualBox.

![VirtualBox_EndeavourOS test - UEFI_10_07_2019_16_18_47](https://user-images.githubusercontent.com/8571419/60976946-dfcba880-a32e-11e9-8e0f-58b66e9af99f.png)

So a tweaking is needed in liveuser profile.

**Comment by FredBezies** [comment]
After installation, all is OK. Wallpaper is shown. Annoying.

**Comment by killajoe** [comment]
> After installation, all is OK. Wallpaper is shown. Annoying.

sorry for that.. i do paste in the wrong [xfce4-desktop.xml](https://github.com/endeavouros-team/liveuser-desktop-settings/blob/master/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml) for the live-session...
