### ISSUE TITLE
There is no mail client by default.

### ISSUE THREAD

**Issue by FredBezies** [endeavouros-team/archiso-offlineinstaller#5]
Simple to reproduce.

1. Install EndeavourOS
2. Open EndeavourOS menu
3. Click on Mail client icon
4. You'll get a dialog box asking you to select a mail client. Sorry for the french version in the screenshot.

![VirtualBox_EndeavourOS test - UEFI_10_07_2019_16_29_15](https://user-images.githubusercontent.com/8571419/60977513-ead30880-a32f-11e9-8967-6ed3ef9ff617.png)

Providing either Mozilla Thunderbird or Claws Mail can fix this issue.

**Comment by killajoe** [comment]
not an issue this is xfce4 default behavior, as it does not ship its own email client like GNOME or KDE 
(french is o.k. for me _La langue de la cuisine_ )
