### ISSUE TITLE
Replacing cmake, ghex and elinks by gvfs plugins?

### ISSUE THREAD

**Issue by FredBezies** [endeavouros-team/archiso-offlineinstaller#6]
While testing a freshly built ISO, I noticed I can remove without problem these softwares:

- cmake
- ghex
- elinks

What about replacing them by gvfs plugins like smb one? It will take something like 29Mb.

![VirtualBox_EndeavourOS test - UEFI_10_07_2019_16_33_15](https://user-images.githubusercontent.com/8571419/60977907-86fd0f80-a330-11e9-8fa5-26b66df3d911.png)

Removing cmake, ghex and elinks? 41 mb... So :)

![VirtualBox_EndeavourOS test - UEFI_10_07_2019_16_35_05](https://user-images.githubusercontent.com/8571419/60978038-c9bee780-a330-11e9-975b-60183e006f62.png)

It is a better user experience to have a fully working gvfs instead of getting elinks...

**Comment by killajoe** [comment]
sure i was removing as much as i find removable, as we want to have most of the tools for the ISO itself to use it as a rescue system, cmake is needed for the installer, but we can safely remove for the installed system. elinks also and some leftover qt stuff .. and ghex 
I will do that later.. 

```
extra/gvfs 1.40.1-2 
    Virtual filesystem implementation for GIO
extra/gvfs-afc 1.40.1-2 
    Virtual filesystem implementation for GIO (AFC backend; Apple mobile devices)
extra/gvfs-goa 1.40.1-2 
    Virtual filesystem implementation for GIO (Gnome Online Accounts backend; cloud storage)
extra/gvfs-gphoto2 1.40.1-2 
    Virtual filesystem implementation for GIO (gphoto2 backend; PTP camera, MTP media player)
extra/gvfs-mtp 1.40.1-2 
    Virtual filesystem implementation for GIO (MTP backend; Android, media player)
extra/gvfs-nfs 1.40.1-2 
    Virtual filesystem implementation for GIO (NFS backend)
extra/gvfs-smb 1.40.1-2 
    Virtual filesystem implementation for GIO (SMB/CIFS backend; Windows client)
```
will be added also

**Comment by killajoe** [comment]
done

**Comment by FredBezies** [comment]
Partially done. I still can see ghex in packages.x86_64 file.

**Comment by killajoe** [comment]
> Partially done. I still can see ghex in packages.x86_64 file.

it will be not installed on system, only there for Live-Session
