### ISSUE TITLE
installed system defaults to LANG=en_US.UTF-8

### ISSUE THREAD

**Issue by killajoe** [endeavouros-team/archiso-offlineinstaller#8]
caused by this ?
https://github.com/endeavouros-team/archiso-offlineinstaller/blob/1aeaff6be1158120191ec3a159fb047d789f307f/airootfs/etc/locale.conf#L1
i do have **LANG=en_US.UTF-8** inside locale.conf all others are setting to DE_

```
[joe@joe-pc ~]$ cat /etc/locale.conf
LANG=en_US.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_MONETARY=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_NUMERIC=de_DE.UTF-8
LC_PAPER=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
```
and /etc/locale.gen has only **en_US.UTF-8** uncommented...

**Comment by FredBezies** [comment]
Cannot reproduce this bug with an up-to-date homemade ISO and installing it in a VirtualBox machine.

Here is a screenshot with /etc/locale.conf

![VirtualBox_Endos - test_13_07_2019_21_41_55](https://user-images.githubusercontent.com/8571419/61175871-1f0c2a80-a5b7-11e9-9737-fe3161edb156.png)

**Comment by killajoe** [comment]
Yes it was me mixing german and english on installation... as i may do not change the Language on the first slide ...
